disabled_rules:
 - nesting
 - class_delegate_protocol

opt_in_rules:
  - explicit_init
  - empty_count
  - redundant_nil_coalescing
  - switch_case_on_newline
  - conditional_returns_on_newline
  - closure_spacing
  - sorted_imports
  - attributes
  - yoda_condition
  - literal_expression_end_indentation
  - unneeded_parentheses_in_closure_argument

excluded:
  - Pods

identifier_name:
  min_length: 1
  max_length: 50

type_name:
  min_length: 1
  max_length: 50
